import {
	AdminDataProps,
	CompanyDataProps,
	DriverDataProps,
	LogisticsDriverDataProps,
	OrderDataProps,
	RevenueDataProps,
	ReviewDataProps,
	RideDataProps,
	RiderDataProps,
	SignUpRequestsCabHailingDataProps,
	SignUpRequestsLogisticsDataProps,
	UsersDataProps,
	RidesInvoiceDataProps,
	VehicleDatabaseProps,
	HangoutsHotelsProps,
	HangoutsLoungesProps,
	HangoutsRestaurantsProps,
} from "./dataTypes";

export const adminData: AdminDataProps = {
	adminName: "Leo",
	totalDrivers: 3591,
	totalRiders: 4126,
	totalManagers: 2300,
	totalUsers: 4434,
	totalRevenue: 848123,
	totalMinedCoins: 200000,
};
const headers = [
	"Ride Id",
	"Driver Name",
	"User Name",
	"Pick/Drop Address",
	"Date",
	"Fare",
	"Status",
	"Vehicle Type",
];
export const rideData: RideDataProps[] = [
	{
		rideId: 9121,
		driverName: "Sammy Priest",
		userName: "Great Ochuko",
		pickAddress: "5, Crescent Base Avenue",
		dropAddress: " 4 Imaralu Drive",
		date: "30/07/2024",
		fare: 3000,
		status: "Cancelled",
		vehicleType: "Toyota Camry, Blue",
	},
	{
		rideId: 9122,
		driverName: "Faith Charlie",
		userName: "Khalid Ochuko",
		pickAddress: "5, Crescent Base Avenue",
		dropAddress: " 4 Imaralu Drive",
		date: "30/07/2024",
		fare: 4500,
		status: "Completed",
		vehicleType: "Toyota Corolla, Pink",
	},
	{
		rideId: 9123,
		driverName: "Eloghene Emobor",
		userName: "Victor Eromosele",
		pickAddress: "5, Crescent Base Avenue",
		dropAddress: " 4 Imaralu Drive",
		date: "30/07/2024",
		fare: 2500,
		status: "Ongoing",
		vehicleType: "Toyota Yaris, Grey",
	},
	{
		rideId: 9124,
		driverName: "Kelvin Zayn",
		userName: "Aviele Michael",
		pickAddress: "5, Crescent Base Avenue",
		dropAddress: " 4 Imaralu Drive",
		date: "30/07/2024",
		fare: 3800,
		status: "Cancelled",
		vehicleType: "Mercedes Benz, White",
	},
	{
		rideId: 9125,
		driverName: "Sammy Priest",
		userName: "Great Ochuko",
		pickAddress: "5, Crescent Base Avenue",
		dropAddress: " 4 Imaralu Drive",
		date: "30/07/2024",
		fare: 3100,
		status: "Cancelled",
		vehicleType: "Honda Accord, Green",
	},
	{
		rideId: 9126,
		driverName: "Faith Charlie",
		userName: "Khalid Ochuko",
		pickAddress: "5, Crescent Base Avenue",
		dropAddress: " 4 Imaralu Drive",
		date: "30/07/2024",
		fare: 1700,
		status: "Completed",
		vehicleType: "Hyundai Sonanta, Silver",
	},

	{
		rideId: 9127,
		driverName: "Eloghene Emobor",
		userName: "Victor Eromosele",
		pickAddress: "5, Crescent Base Avenue",
		dropAddress: " 4 Imaralu Drive",
		date: "30/07/2024",
		fare: 2500,
		status: "Ongoing",
		vehicleType: "Toyota Yaris, Grey",
	},
	{
		rideId: 9128,
		driverName: "Kelvin Zayn",
		userName: "Aviele Michael",
		pickAddress: "5, Crescent Base Avenue",
		dropAddress: " 4 Imaralu Drive",
		date: "30/07/2024",
		fare: 3800,
		status: "Cancelled",
		vehicleType: "Mercedes Benz, White",
	},
	{
		rideId: 9129,
		driverName: "Sammy Priest",
		userName: "Great Ochuko",
		pickAddress: "5, Crescent Base Avenue",
		dropAddress: " 4 Imaralu Drive",
		date: "30/07/2024",
		fare: 3000,
		status: "Cancelled",
		vehicleType: "Toyota Camry, Blue",
	},
	{
		rideId: 9130,
		driverName: "Faith Charlie",
		userName: "Khalid Ochuko",
		pickAddress: "5, Crescent Base Avenue",
		dropAddress: " 4 Imaralu Drive",
		date: "30/07/2024",
		fare: 4500,
		status: "Completed",
		vehicleType: "Toyota Corolla, Pink",
	},
	{
		rideId: 9131,
		driverName: "Eloghene Emobor",
		userName: "Victor Eromosele",
		pickAddress: "5, Crescent Base Avenue",
		dropAddress: " 4 Imaralu Drive",
		date: "30/07/2024",
		fare: 2500,
		status: "Ongoing",
		vehicleType: "Toyota Yaris, Grey",
	},
	{
		rideId: 9132,
		driverName: "Kelvin Zayn",
		userName: "Aviele Michael",
		pickAddress: "5, Crescent Base Avenue",
		dropAddress: " 4 Imaralu Drive",
		date: "30/07/2024",
		fare: 3800,
		status: "Cancelled",
		vehicleType: "Mercedes Benz, White",
	},
	{
		rideId: 9133,
		driverName: "Sammy Priest",
		userName: "Great Ochuko",
		pickAddress: "5, Crescent Base Avenue",
		dropAddress: " 4 Imaralu Drive",
		date: "30/07/2024",
		fare: 3100,
		status: "Cancelled",
		vehicleType: "Honda Accord, Green",
	},
	{
		rideId: 9134,
		driverName: "Faith Charlie",
		userName: "Khalid Ochuko",
		pickAddress: "5, Crescent Base Avenue",
		dropAddress: " 4 Imaralu Drive",
		date: "30/07/2024",
		fare: 1700,
		status: "Completed",
		vehicleType: "Hyundai Sonanta, Silver",
	},
	{
		rideId: 9135,
		driverName: "Kelvin Zayn",
		userName: "Aviele Michael",
		pickAddress: "5, Crescent Base Avenue",
		dropAddress: " 4 Imaralu Drive",
		date: "30/07/2024",
		fare: 3800,
		status: "Cancelled",
		vehicleType: "Mercedes Benz, White",
	},
	{
		rideId: 9136,
		driverName: "Sammy Priest",
		userName: "Great Ochuko",
		pickAddress: "5, Crescent Base Avenue",
		dropAddress: " 4 Imaralu Drive",
		date: "30/07/2024",
		fare: 3100,
		status: "Cancelled",
		vehicleType: "Honda Accord, Green",
	},

	{
		rideId: 9137,
		driverName: "Eloghene Emobor",
		userName: "Victor Eromosele",
		pickAddress: "5, Crescent Base Avenue",
		dropAddress: " 4 Imaralu Drive",
		date: "30/07/2024",
		fare: 2500,
		status: "Ongoing",
		vehicleType: "Toyota Yaris, Grey",
	},
	{
		rideId: 9138,
		driverName: "Kelvin Zayn",
		userName: "Aviele Michael",
		pickAddress: "5, Crescent Base Avenue",
		dropAddress: " 4 Imaralu Drive",
		date: "30/07/2024",
		fare: 3800,
		status: "Cancelled",
		vehicleType: "Mercedes Benz, White",
	},
	{
		rideId: 9139,
		driverName: "Sammy Priest",
		userName: "Great Ochuko",
		pickAddress: "5, Crescent Base Avenue",
		dropAddress: " 4 Imaralu Drive",
		date: "30/07/2024",
		fare: 3100,
		status: "Cancelled",
		vehicleType: "Honda Accord, Green",
	},
	{
		rideId: 9140,
		driverName: "Kelvin Zayn",
		userName: "Aviele Michael",
		pickAddress: "5, Crescent Base Avenue",
		dropAddress: " 4 Imaralu Drive",
		date: "30/07/2024",
		fare: 3800,
		status: "Cancelled",
		vehicleType: "Mercedes Benz, White",
	},
	{
		rideId: 9141,
		driverName: "Sammy Priest",
		userName: "Great Ochuko",
		pickAddress: "5, Crescent Base Avenue",
		dropAddress: " 4 Imaralu Drive",
		date: "30/07/2024",
		fare: 3100,
		status: "Cancelled",
		vehicleType: "Honda Accord, Green",
	},
	{
		rideId: 9142,
		driverName: "Eloghene Emobor",
		userName: "Victor Eromosele",
		pickAddress: "5, Crescent Base Avenue",
		dropAddress: " 4 Imaralu Drive",
		date: "30/07/2024",
		fare: 2500,
		status: "Ongoing",
		vehicleType: "Toyota Yaris, Grey",
	},
];

export const companyData: CompanyDataProps[] = [
	{
		managerId: 9121,
		companyName: "Sammy Priest",
		companyId: "2345678asd345",
		noOfRiders: 2789,
	},
	{
		managerId: 9122,
		companyName: "Khalid Maurice",
		companyId: "2345678asd345",
		noOfRiders: 2129,
	},
	{
		managerId: 9123,
		companyName: "Victor Eromosele",
		companyId: "2345678asd345",
		noOfRiders: 6789,
	},
	{
		managerId: 9124,
		companyName: "Aviele Michael",
		companyId: "2345678asd345",
		noOfRiders: 4289,
	},
	{
		managerId: 9125,
		companyName: "Ewu Ogun",
		companyId: "2345678asd345",
		noOfRiders: 279,
	},
	{
		managerId: 9126,
		companyName: "Matthew Chuks",
		companyId: "2345678asd345",
		noOfRiders: 1089,
	},
	{
		managerId: 9127,
		companyName: "Doris Hellhound",
		companyId: "2345678asd345",
		noOfRiders: 2789,
	},
	{
		managerId: 9128,
		companyName: "Ben Bruce",
		companyId: "2345678asd345",
		noOfRiders: 2129,
	},
	{
		managerId: 9129,
		companyName: "Favour Real",
		companyId: "2345678asd345",
		noOfRiders: 6789,
	},
	{
		managerId: 9130,
		companyName: "Shaun Michael",
		companyId: "2345678asd345",
		noOfRiders: 4289,
	},
	{
		managerId: 9131,
		companyName: "Wilson Osun",
		companyId: "2345678asd345",
		noOfRiders: 279,
	},
	{
		managerId: 9132,
		companyName: "Bondzie Chuks",
		companyId: "2345678asd345",
		noOfRiders: 1089,
	},
	{
		managerId: 9133,
		companyName: "Aviele Michael",
		companyId: "2345678asd345",
		noOfRiders: 4289,
	},
	{
		managerId: 9134,
		companyName: "Ewu Ogun",
		companyId: "2345678asd345",
		noOfRiders: 279,
	},
	{
		managerId: 9135,
		companyName: "Matthew Chuks",
		companyId: "2345678asd345",
		noOfRiders: 1089,
	},
	{
		managerId: 9136,
		companyName: "Doris Hellhound",
		companyId: "2345678asd345",
		noOfRiders: 2789,
	},
	{
		managerId: 9137,
		companyName: "Ben Bruce",
		companyId: "2345678asd345",
		noOfRiders: 2129,
	},
	{
		managerId: 9138,
		companyName: "Ben Bruce",
		companyId: "2345678asd345",
		noOfRiders: 2129,
	},
	{
		managerId: 9139,
		companyName: "Favour Real",
		companyId: "2345678asd345",
		noOfRiders: 6789,
	},
	{
		managerId: 9140,
		companyName: "Shaun Michael",
		companyId: "2345678asd345",
		noOfRiders: 4289,
	},
	{
		managerId: 9141,
		companyName: "Favour Real",
		companyId: "2345678asd345",
		noOfRiders: 6789,
	},
];

export const logisticsDriverData: LogisticsDriverDataProps[] = [
	{
		driverId: 9121,
		companyName: "Sammy Priest",
		vehicleType: "Toyota Camry, Blue",
		fare: 2789,
	},
	{
		driverId: 9122,
		companyName: "Khalid Maurice",
		vehicleType: "Dodge Chaeger , Black",
		fare: 2129,
	},
	{
		driverId: 9123,
		companyName: "Victor Eromosele",
		vehicleType: "Lamborghini Urus, Green",
		fare: 6789,
	},
	{
		driverId: 9124,
		companyName: "Aviele Michael",
		vehicleType: "Lexus is350, Red",
		fare: 4289,
	},
	{
		driverId: 9125,
		companyName: "Ewu Ogun",
		vehicleType: "Toyota Supra, Black",
		fare: 279,
	},
	{
		driverId: 9126,
		companyName: "Matthew Chuks",
		vehicleType: "Mercedes Benz C63, Grey",
		fare: 1089,
	},
	{
		driverId: 9127,
		companyName: "Doris Hellhound",
		vehicleType: "Lexus LC500, Black",
		fare: 2789,
	},
	{
		driverId: 9128,
		companyName: "Ben Bruce",
		vehicleType: "Ford Mustang, White",
		fare: 2129,
	},
	{
		driverId: 9129,
		companyName: "Favour Real",
		vehicleType: "Bugatti Veyron, Black",
		fare: 6789,
	},
	{
		driverId: 9130,
		companyName: "Shaun Michael",
		vehicleType: "McLaren F1, Silver",
		fare: 4289,
	},
	{
		driverId: 9131,
		companyName: "Wilson Osun",
		vehicleType: "Bugatti Chiron, Blue",
		fare: 279,
	},
	{
		driverId: 9132,
		companyName: "Bondzie Chuks",
		vehicleType: "Ferrari F40, Red",
		fare: 1089,
	},
	{
		driverId: 9133,
		companyName: "Aviele Michael",
		vehicleType: "Ferrari 430, Red",
		fare: 4289,
	},
	{
		driverId: 9134,
		companyName: "Ewu Ogun",
		vehicleType: "Aston Martin Vantage, Black",
		fare: 279,
	},
	{
		driverId: 9135,
		companyName: "Matthew Chuks",
		vehicleType: "Wiesmann MF5, White",
		fare: 1089,
	},
	{
		driverId: 9136,
		companyName: "Doris Hellhound",
		vehicleType: "Jaguar F-type, Blue",
		fare: 2789,
	},
	{
		driverId: 9137,
		companyName: "Ben Bruce",
		vehicleType: "Mercedes-Benz SLS, White",
		fare: 2129,
	},
	{
		driverId: 9138,
		companyName: "Ben Bruce",
		vehicleType: "TVR Sagaris, Silver",
		fare: 2129,
	},
	{
		driverId: 9139,
		companyName: "Favour Real",
		vehicleType: "BMW Z8, Silver",
		fare: 6789,
	},
	{
		driverId: 9140,
		companyName: "Shaun Michael",
		vehicleType: "Pagani Zonda,  Silver",
		fare: 4289,
	},
	{
		driverId: 9141,
		companyName: "Favour Real",
		vehicleType: "Ford GT, Blue",
		fare: 6789,
	},
];

export const riderData: RiderDataProps[] = [
	{
		driverId: 9121,
		companyName: "Sammy Priest",
		vehicleType: "Toyota Camry, Blue",
		packagesDelivered: 2789,
	},
	{
		driverId: 9122,
		companyName: "Khalid Maurice",
		vehicleType: "Dodge Chaeger , Black",
		packagesDelivered: 2129,
	},
	{
		driverId: 9123,
		companyName: "Victor Eromosele",
		vehicleType: "Lamborghini Urus, Green",
		packagesDelivered: 6789,
	},
	{
		driverId: 9124,
		companyName: "Aviele Michael",
		vehicleType: "Lexus is350, Red",
		packagesDelivered: 4289,
	},
	{
		driverId: 9125,
		companyName: "Ewu Ogun",
		vehicleType: "Toyota Supra, Black",
		packagesDelivered: 279,
	},
	{
		driverId: 9126,
		companyName: "Matthew Chuks",
		vehicleType: "Mercedes Benz C63, Grey",
		packagesDelivered: 1089,
	},
	{
		driverId: 9127,
		companyName: "Doris Hellhound",
		vehicleType: "Lexus LC500, Black",
		packagesDelivered: 2789,
	},
	{
		driverId: 9128,
		companyName: "Ben Bruce",
		vehicleType: "Ford Mustang, White",
		packagesDelivered: 2129,
	},
	{
		driverId: 9129,
		companyName: "Favour Real",
		vehicleType: "Bugatti Veyron, Black",
		packagesDelivered: 6789,
	},
	{
		driverId: 9130,
		companyName: "Shaun Michael",
		vehicleType: "McLaren F1, Silver",
		packagesDelivered: 4289,
	},
	{
		driverId: 9131,
		companyName: "Wilson Osun",
		vehicleType: "Bugatti Chiron, Blue",
		packagesDelivered: 279,
	},
	{
		driverId: 9132,
		companyName: "Bondzie Chuks",
		vehicleType: "Ferrari F40, Red",
		packagesDelivered: 1089,
	},
	{
		driverId: 9133,
		companyName: "Aviele Michael",
		vehicleType: "Ferrari 430, Red",
		packagesDelivered: 4289,
	},
	{
		driverId: 9134,
		companyName: "Ewu Ogun",
		vehicleType: "Aston Martin Vantage, Black",
		packagesDelivered: 279,
	},
	{
		driverId: 9135,
		companyName: "Matthew Chuks",
		vehicleType: "Wiesmann MF5, White",
		packagesDelivered: 1089,
	},
	{
		driverId: 9136,
		companyName: "Doris Hellhound",
		vehicleType: "Jaguar F-type, Blue",
		packagesDelivered: 2789,
	},
	{
		driverId: 9137,
		companyName: "Ben Bruce",
		vehicleType: "Mercedes-Benz SLS, White",
		packagesDelivered: 2129,
	},
	{
		driverId: 9138,
		companyName: "Ben Bruce",
		vehicleType: "TVR Sagaris, Silver",
		packagesDelivered: 2129,
	},
	{
		driverId: 9139,
		companyName: "Favour Real",
		vehicleType: "BMW Z8, Silver",
		packagesDelivered: 6789,
	},
	{
		driverId: 9140,
		companyName: "Shaun Michael",
		vehicleType: "Pagani Zonda,  Silver",
		packagesDelivered: 4289,
	},
	{
		driverId: 9141,
		companyName: "Favour Real",
		vehicleType: "Ford GT, Blue",
		packagesDelivered: 6789,
	},
];

export const orderData: OrderDataProps[] = [
	{
		orderId: 9121,
		deliveredBy: "Sammy Priest",
		deliveredTo: "Great Ochuko",
		pickUp: "5, Crescent Base Avenue",
		destination: " 4 Imaralu Drive",
		completionTime: "30-07-2024",
	},
	{
		orderId: 9122,
		deliveredBy: "Faith Charlie",
		deliveredTo: "Khalid Ochuko",
		pickUp: "5, Crescent Base Avenue",
		destination: " 4 Imaralu Drive",
		completionTime: "30-07-2024",
	},
	{
		orderId: 9123,
		deliveredBy: "Eloghene Emobor",
		deliveredTo: "Victor Eromosele",
		pickUp: "5, Crescent Base Avenue",
		destination: " 4 Imaralu Drive",
		completionTime: "30-07-2024",
	},
	{
		orderId: 9124,
		deliveredBy: "Kelvin Zayn",
		deliveredTo: "Aviele Michael",
		pickUp: "5, Crescent Base Avenue",
		destination: " 4 Imaralu Drive",
		completionTime: "30-07-2024",
	},
	{
		orderId: 9125,
		deliveredBy: "Sammy Priest",
		deliveredTo: "Great Ochuko",
		pickUp: "5, Crescent Base Avenue",
		destination: " 4 Imaralu Drive",
		completionTime: "30-07-2024",
	},
	{
		orderId: 9126,
		deliveredBy: "Faith Charlie",
		deliveredTo: "Khalid Ochuko",
		pickUp: "5, Crescent Base Avenue",
		destination: " 4 Imaralu Drive",
		completionTime: "30-07-2024",
	},

	{
		orderId: 9127,
		deliveredBy: "Eloghene Emobor",
		deliveredTo: "Victor Eromosele",
		pickUp: "5, Crescent Base Avenue",
		destination: " 4 Imaralu Drive",
		completionTime: "30-07-2024",
	},
	{
		orderId: 9128,
		deliveredBy: "Kelvin Zayn",
		deliveredTo: "Aviele Michael",
		pickUp: "5, Crescent Base Avenue",
		destination: " 4 Imaralu Drive",
		completionTime: "30-07-2024",
	},
	{
		orderId: 9129,
		deliveredBy: "Sammy Priest",
		deliveredTo: "Great Ochuko",
		pickUp: "5, Crescent Base Avenue",
		destination: " 4 Imaralu Drive",
		completionTime: "30-07-2024",
	},
	{
		orderId: 9130,
		deliveredBy: "Faith Charlie",
		deliveredTo: "Khalid Ochuko",
		pickUp: "5, Crescent Base Avenue",
		destination: " 4 Imaralu Drive",
		completionTime: "30-07-2024",
	},
	{
		orderId: 9131,
		deliveredBy: "Eloghene Emobor",
		deliveredTo: "Victor Eromosele",
		pickUp: "5, Crescent Base Avenue",
		destination: " 4 Imaralu Drive",
		completionTime: "30-07-2024",
	},
	{
		orderId: 9132,
		deliveredBy: "Kelvin Zayn",
		deliveredTo: "Aviele Michael",
		pickUp: "5, Crescent Base Avenue",
		destination: " 4 Imaralu Drive",
		completionTime: "30-07-2024",
	},
	{
		orderId: 9133,
		deliveredBy: "Sammy Priest",
		deliveredTo: "Great Ochuko",
		pickUp: "5, Crescent Base Avenue",
		destination: " 4 Imaralu Drive",
		completionTime: "30-07-2024",
	},
	{
		orderId: 9134,
		deliveredBy: "Faith Charlie",
		deliveredTo: "Khalid Ochuko",
		pickUp: "5, Crescent Base Avenue",
		destination: " 4 Imaralu Drive",
		completionTime: "30-07-2024",
	},
	{
		orderId: 9135,
		deliveredBy: "Kelvin Zayn",
		deliveredTo: "Aviele Michael",
		pickUp: "5, Crescent Base Avenue",
		destination: " 4 Imaralu Drive",
		completionTime: "30-07-2024",
	},
	{
		orderId: 9136,
		deliveredBy: "Sammy Priest",
		deliveredTo: "Great Ochuko",
		pickUp: "5, Crescent Base Avenue",
		destination: " 4 Imaralu Drive",
		completionTime: "30-07-2024",
	},

	{
		orderId: 9137,
		deliveredBy: "Eloghene Emobor",
		deliveredTo: "Victor Eromosele",
		pickUp: "5, Crescent Base Avenue",
		destination: " 4 Imaralu Drive",
		completionTime: "30-07-2024",
	},
	{
		orderId: 9138,
		deliveredBy: "Kelvin Zayn",
		deliveredTo: "Aviele Michael",
		pickUp: "5, Crescent Base Avenue",
		destination: " 4 Imaralu Drive",
		completionTime: "30-07-2024",
	},
	{
		orderId: 9139,
		deliveredBy: "Sammy Priest",
		deliveredTo: "Great Ochuko",
		pickUp: "5, Crescent Base Avenue",
		destination: " 4 Imaralu Drive",
		completionTime: "30-07-2024",
	},
	{
		orderId: 9140,
		deliveredBy: "Kelvin Zayn",
		deliveredTo: "Aviele Michael",
		pickUp: "5, Crescent Base Avenue",
		destination: " 4 Imaralu Drive",
		completionTime: "30-07-2024",
	},
	{
		orderId: 9141,
		deliveredBy: "Sammy Priest",
		deliveredTo: "Great Ochuko",
		pickUp: "5, Crescent Base Avenue",
		destination: " 4 Imaralu Drive",
		completionTime: "30-07-2024",
	},
	{
		orderId: 9142,
		deliveredBy: "Eloghene Emobor",
		deliveredTo: "Victor Eromosele",
		pickUp: "5, Crescent Base Avenue",
		destination: " 4 Imaralu Drive",
		completionTime: "30-07-2024",
	},
];

export const signUpRequestsCabHailingData: SignUpRequestsCabHailingDataProps[] =
	[
		{
			id: 1,
			name: "AlexJohnson",
			vehicleType: "Coupe",
			vehicleNumber: "ZB1234XY",
			status: "Pending",
			date: "05-10-2024",
		},
		{
			id: 2,
			name: "MiaTurner",
			vehicleType: "Convertible",
			vehicleNumber: "CF7891YZ",
			status: "Approved",
			date: "06-10-2024",
		},
		{
			id: 3,
			name: "EthanGreen",
			vehicleType: "Van",
			vehicleNumber: "GH4567WX",
			status: "Declined",
			date: "07-10-2024",
		},
		{
			id: 4,
			name: "SophiaBrown",
			vehicleType: "Luxury",
			vehicleNumber: "IJ8901UV",
			status: "Pending",
			date: "08-10-2024",
		},
		{
			id: 5,
			name: "LiamScott",
			vehicleType: "Minivan",
			vehicleNumber: "KM1234RS",
			status: "Approved",
			date: "09-10-2024",
		},
		{
			id: 6,
			name: "OliviaHall",
			vehicleType: "Crossover",
			vehicleNumber: "NL5678MN",
			status: "Declined",
			date: "10-10-2024",
		},
		{
			id: 7,
			name: "MasonClark",
			vehicleType: "Wagon",
			vehicleNumber: "PO3456PQ",
			status: "Approved",
			date: "11-10-2024",
		},
		{
			id: 8,
			name: "AvaLopez",
			vehicleType: "Compact",
			vehicleNumber: "QR7890KL",
			status: "Pending",
			date: "12-10-2024",
		},
		{
			id: 9,
			name: "JamesYoung",
			vehicleType: "Motorcycle",
			vehicleNumber: "ST1234OP",
			status: "Declined",
			date: "13-10-2024",
		},
		{
			id: 10,
			name: "EllaKing",
			vehicleType: "Pickup",
			vehicleNumber: "UV5678QR",
			status: "Approved",
			date: "14-10-2024",
		},
		{
			id: 11,
			name: "LucasWalker",
			vehicleType: "Hybrid",
			vehicleNumber: "WX9012TU",
			status: "Pending",
			date: "15-10-2024",
		},
		{
			id: 12,
			name: "IsabellaMitchell",
			vehicleType: "Electric",
			vehicleNumber: "YZ3456VW",
			status: "Approved",
			date: "16-10-2024",
		},
		{
			id: 13,
			name: "BenjaminPerez",
			vehicleType: "Coupe",
			vehicleNumber: "BA2345XY",
			status: "Declined",
			date: "17-10-2024",
		},
		{
			id: 14,
			name: "AmeliaReed",
			vehicleType: "Convertible",
			vehicleNumber: "CF6789YZ",
			status: "Pending",
			date: "18-10-2024",
		},
		{
			id: 15,
			name: "HenryBaker",
			vehicleType: "Luxury",
			vehicleNumber: "GH9012WX",
			status: "Approved",
			date: "19-10-2024",
		},
		{
			id: 16,
			name: "CharlotteRivera",
			vehicleType: "Van",
			vehicleNumber: "IJ3456UV",
			status: "Declined",
			date: "20-10-2024",
		},
		{
			id: 17,
			name: "DanielWard",
			vehicleType: "Pickup",
			vehicleNumber: "KM7890RS",
			status: "Pending",
			date: "21-10-2024",
		},
		{
			id: 18,
			name: "HarperTorres",
			vehicleType: "Wagon",
			vehicleNumber: "NL1234MN",
			status: "Approved",
			date: "22-10-2024",
		},
		{
			id: 19,
			name: "MichaelSanchez",
			vehicleType: "Motorcycle",
			vehicleNumber: "PO5678PQ",
			status: "Declined",
			date: "23-10-2024",
		},
		{
			id: 20,
			name: "AbigailCampbell",
			vehicleType: "Hybrid",
			vehicleNumber: "QR9012KL",
			status: "Approved",
			date: "24-10-2024",
		},
	];

export const signUpRequestsLogisticsData: SignUpRequestsLogisticsDataProps[] = [
	{
		id: 1,
		name: "John Doe",
		vehicleType: "Sedan",
		vehicleNumber: "AB1234XY",
		status: "Approved",
		date: "12-09-2024",
	},
	{
		id: 2,
		name: "Jane Smith",
		vehicleType: "SUV",
		vehicleNumber: "CD5678YZ",
		status: "Pending",
		date: "13-09-2024",
	},
	{
		id: 3,
		name: "Paul Brown",
		vehicleType: "Hatchback",
		vehicleNumber: "EF9012WX",
		status: "Declined",
		date: "14-09-2024",
	},
	{
		id: 4,
		name: "Emily Davis",
		vehicleType: "Sedan",
		vehicleNumber: "GH3456UV",
		status: "Approved",
		date: "15-09-2024",
	},
	{
		id: 5,
		name: "Chris Wilson",
		vehicleType: "Truck",
		vehicleNumber: "IJ7890RS",
		status: "Pending",
		date: "16-09-2024",
	},
	{
		id: 6,
		name: "Nancy Miller",
		vehicleType: "SUV",
		vehicleNumber: "KL2345MN",
		status: "Approved",
		date: "17-09-2024",
	},
	{
		id: 7,
		name: "Steve Moore",
		vehicleType: "Sedan",
		vehicleNumber: "OP6789PQ",
		status: "Declined",
		date: "18-09-2024",
	},
	{
		id: 8,
		name: "Rachel Taylor",
		vehicleType: "Hatchback",
		vehicleNumber: "QR1234KL",
		status: "Approved",
		date: "19-09-2024",
	},
	{
		id: 9,
		name: "David Anderson",
		vehicleType: "Truck",
		vehicleNumber: "ST5678OP",
		status: "Pending",
		date: "20-09-2024",
	},
	{
		id: 10,
		name: "Linda Thomas",
		vehicleType: "SUV",
		vehicleNumber: "UV9012QR",
		status: "Approved",
		date: "21-09-2024",
	},
	{
		id: 11,
		name: "Mark Jackson",
		vehicleType: "Sedan",
		vehicleNumber: "WX3456TU",
		status: "Declined",
		date: "22-09-2024",
	},
	{
		id: 12,
		name: "Susan White",
		vehicleType: "Hatchback",
		vehicleNumber: "YZ7890VW",
		status: "Approved",
		date: "23-09-2024",
	},
	{
		id: 13,
		name: "Kevin Harris",
		vehicleType: "Truck",
		vehicleNumber: "AB2345XY",
		status: "Pending",
		date: "24-09-2024",
	},
	{
		id: 14,
		name: "Jessica Martin",
		vehicleType: "SUV",
		vehicleNumber: "CD5678YZ",
		status: "Approved",
		date: "25-09-2024",
	},
	{
		id: 15,
		name: "Daniel Thompson",
		vehicleType: "Sedan",
		vehicleNumber: "EF9012WX",
		status: "Declined",
		date: "26-09-2024",
	},
	{
		id: 16,
		name: "Laura Garcia",
		vehicleType: "Truck",
		vehicleNumber: "GH3456UV",
		status: "Approved",
		date: "27-09-2024",
	},
	{
		id: 17,
		name: "James Martinez",
		vehicleType: "Hatchback",
		vehicleNumber: "IJ7890RS",
		status: "Pending",
		date: "28-09-2024",
	},
	{
		id: 18,
		name: "Sarah Robinson",
		vehicleType: "SUV",
		vehicleNumber: "KL2345MN",
		status: "Approved",
		date: "29-09-2024",
	},
	{
		id: 19,
		name: "Brian Clark",
		vehicleType: "Sedan",
		vehicleNumber: "OP6789PQ",
		status: "Declined",
		date: "30-09-2024",
	},
	{
		id: 20,
		name: "Karen Rodriguez",
		vehicleType: "Truck",
		vehicleNumber: "QR1234KL",
		status: "Approved",
		date: "01-10-2024",
	},
];

export const usersData: UsersDataProps[] = [
	{
		userId: 9121,
		email: "alex.johnson@gmail.com",
		contactNo: 2348012345612,
		verification: "Verified",
		reviews: 4.0,
		totalRides: 120,
		cancelledRides: 3,
		completedRides: 117,
		amountSpent: 54000,
		data: [
			{
				date: "22-jul-2024",
				time: "18:08",
				pickupAddress: "123 Main St",
				destination: "456 Elm St",
				cost: 15.5,
				coinsMined: 0.0000000023,
				distanceCovered: 2.4,
			},
			{
				date: "23-jul-2024",
				time: "12:45",
				pickupAddress: "78 Oak Ave",
				destination: "912 Pine St",
				cost: 20.0,
				coinsMined: 0.0000000031,
				distanceCovered: 5.1,
			},
			{
				date: "24-jul-2024",
				time: "14:15",
				pickupAddress: "321 Maple St",
				destination: "789 Cedar St",
				cost: 8.75,
				coinsMined: 0.0000000018,
				distanceCovered: 3.0,
			},
			{
				date: "25-jul-2024",
				time: "09:30",
				pickupAddress: "55 Birch Blvd",
				destination: "66 Ash Ct",
				cost: 12.3,
				coinsMined: 0.0000000025,
				distanceCovered: 4.7,
			},
			{
				date: "26-jul-2024",
				time: "16:50",
				pickupAddress: "88 Poplar Pl",
				destination: "22 Willow Rd",
				cost: 18.2,
				coinsMined: 0.000000004,
				distanceCovered: 6.2,
			},
			{
				date: "27-jul-2024",
				time: "08:20",
				pickupAddress: "11 Redwood St",
				destination: "44 Cypress Ln",
				cost: 9.5,
				coinsMined: 0.0000000022,
				distanceCovered: 1.9,
			},
			{
				date: "28-jul-2024",
				time: "19:00",
				pickupAddress: "101 Spruce Dr",
				destination: "202 Chestnut Cir",
				cost: 14.9,
				coinsMined: 0.0000000037,
				distanceCovered: 4.3,
			},
			{
				date: "29-jul-2024",
				time: "17:45",
				pickupAddress: "303 Alder Way",
				destination: "404 Hemlock St",
				cost: 22.1,
				coinsMined: 0.0000000045,
				distanceCovered: 7.5,
			},
			{
				date: "30-jul-2024",
				time: "20:10",
				pickupAddress: "505 Aspen Dr",
				destination: "606 Fir Ct",
				cost: 13.0,
				coinsMined: 0.000000003,
				distanceCovered: 3.6,
			},
			{
				date: "31-jul-2024",
				time: "13:30",
				pickupAddress: "707 Larch Pl",
				destination: "808 Holly Ln",
				cost: 19.2,
				coinsMined: 0.0000000039,
				distanceCovered: 5.9,
			},
			{
				date: "01-aug-2024",
				time: "15:10",
				pickupAddress: "909 Beech Rd",
				destination: "1010 Ivy St",
				cost: 11.7,
				coinsMined: 0.0000000029,
				distanceCovered: 2.8,
			},
			{
				date: "02-aug-2024",
				time: "11:55",
				pickupAddress: "111 Sycamore Ave",
				destination: "121 Willow Ct",
				cost: 10.2,
				coinsMined: 0.0000000026,
				distanceCovered: 1.7,
			},
			{
				date: "03-aug-2024",
				time: "10:25",
				pickupAddress: "131 Walnut St",
				destination: "141 Cherry Cir",
				cost: 16.8,
				coinsMined: 0.0000000034,
				distanceCovered: 5.3,
			},
			{
				date: "04-aug-2024",
				time: "09:15",
				pickupAddress: "151 Plum Ln",
				destination: "161 Grape St",
				cost: 7.9,
				coinsMined: 0.0000000017,
				distanceCovered: 1.2,
			},
			{
				date: "05-aug-2024",
				time: "08:05",
				pickupAddress: "171 Peach Pl",
				destination: "181 Orange Ct",
				cost: 6.5,
				coinsMined: 0.0000000014,
				distanceCovered: 0.8,
			},
			{
				date: "06-aug-2024",
				time: "18:40",
				pickupAddress: "191 Nectarine Rd",
				destination: "201 Lemon Cir",
				cost: 21.4,
				coinsMined: 0.0000000043,
				distanceCovered: 6.8,
			},
			{
				date: "07-aug-2024",
				time: "17:00",
				pickupAddress: "211 Kiwi Dr",
				destination: "221 Fig St",
				cost: 20.9,
				coinsMined: 0.0000000041,
				distanceCovered: 6.5,
			},
			{
				date: "08-aug-2024",
				time: "16:15",
				pickupAddress: "231 Pomegranate Ave",
				destination: "241 Papaya Ln",
				cost: 12.4,
				coinsMined: 0.0000000027,
				distanceCovered: 3.0,
			},
			{
				date: "09-aug-2024",
				time: "13:40",
				pickupAddress: "251 Persimmon St",
				destination: "261 Date Ct",
				cost: 8.6,
				coinsMined: 0.0000000019,
				distanceCovered: 1.5,
			},
			{
				date: "10-aug-2024",
				time: "19:55",
				pickupAddress: "271 Starfruit Pl",
				destination: "281 Mangosteen Rd",
				cost: 24.0,
				coinsMined: 0.000000005,
				distanceCovered: 7.8,
			},
			{
				date: "11-aug-2024",
				time: "21:20",
				pickupAddress: "291 Durian Cir",
				destination: "301 Rambutan St",
				cost: 17.1,
				coinsMined: 0.0000000036,
				distanceCovered: 5.4,
			},
			{
				date: "12-aug-2024",
				time: "07:50",
				pickupAddress: "311 Lychee Rd",
				destination: "321 Coconut Ave",
				cost: 9.3,
				coinsMined: 0.0000000021,
				distanceCovered: 1.4,
			},
			{
				date: "13-aug-2024",
				time: "08:30",
				pickupAddress: "331 Banana Pl",
				destination: "341 Plantain Ln",
				cost: 18.3,
				coinsMined: 0.0000000038,
				distanceCovered: 6.0,
			},
			{
				date: "14-aug-2024",
				time: "11:15",
				pickupAddress: "351 Melon St",
				destination: "361 Cantaloupe Rd",
				cost: 10.7,
				coinsMined: 0.0000000028,
				distanceCovered: 2.7,
			},
			{
				date: "15-aug-2024",
				time: "12:10",
				pickupAddress: "371 Honeydew Cir",
				destination: "381 Watermelon Ct",
				cost: 13.6,
				coinsMined: 0.0000000031,
				distanceCovered: 3.4,
			},
			{
				date: "16-aug-2024",
				time: "14:05",
				pickupAddress: "391 Berry Pl",
				destination: "401 Blueberry Ln",
				cost: 22.5,
				coinsMined: 0.0000000046,
				distanceCovered: 6.9,
			},
			{
				date: "17-aug-2024",
				time: "16:20",
				pickupAddress: "411 Cranberry Rd",
				destination: "421 Strawberry St",
				cost: 11.5,
				coinsMined: 0.0000000027,
				distanceCovered: 3.2,
			},
			{
				date: "18-aug-2024",
				time: "18:00",
				pickupAddress: "431 Raspberry Ave",
				destination: "441 Blackberry Cir",
				cost: 14.1,
				coinsMined: 0.0000000033,
				distanceCovered: 4.0,
			},
			{
				date: "19-aug-2024",
				time: "10:25",
				pickupAddress: "451 Gooseberry Pl",
				destination: "461 Huckleberry Rd",
				cost: 16.0,
				coinsMined: 0.0000000035,
				distanceCovered: 5.2,
			},
		],
	},
	{
		userId: 9122,
		email: "mia.turner@gmail.com",
		contactNo: 2348023456789,
		verification: "Unverified",
		reviews: 3.0,
		totalRides: 75,
		cancelledRides: 1,
		completedRides: 74,
		amountSpent: 32000,
		data: [
			{
				date: "25-jul-2024",
				time: "09:30",
				pickupAddress: "55 Birch Blvd",
				destination: "66 Ash Ct",
				cost: 12.3,
				coinsMined: 0.0000000025,
				distanceCovered: 4.7,
			},
			{
				date: "26-jul-2024",
				time: "16:50",
				pickupAddress: "88 Poplar Pl",
				destination: "22 Willow Rd",
				cost: 18.2,
				coinsMined: 0.000000004,
				distanceCovered: 6.2,
			},
			{
				date: "27-jul-2024",
				time: "08:20",
				pickupAddress: "11 Redwood St",
				destination: "44 Cypress Ln",
				cost: 9.5,
				coinsMined: 0.0000000022,
				distanceCovered: 1.9,
			},
			{
				date: "28-jul-2024",
				time: "19:00",
				pickupAddress: "101 Spruce Dr",
				destination: "202 Chestnut Cir",
				cost: 14.9,
				coinsMined: 0.0000000037,
				distanceCovered: 4.3,
			},
			{
				date: "29-jul-2024",
				time: "17:45",
				pickupAddress: "303 Alder Way",
				destination: "404 Hemlock St",
				cost: 22.1,
				coinsMined: 0.0000000045,
				distanceCovered: 7.5,
			},
			{
				date: "30-jul-2024",
				time: "20:10",
				pickupAddress: "505 Aspen Dr",
				destination: "606 Fir Ct",
				cost: 13.0,
				coinsMined: 0.000000003,
				distanceCovered: 3.6,
			},
			{
				date: "31-jul-2024",
				time: "13:30",
				pickupAddress: "707 Larch Pl",
				destination: "808 Holly Ln",
				cost: 19.2,
				coinsMined: 0.0000000039,
				distanceCovered: 5.9,
			},
			{
				date: "01-aug-2024",
				time: "15:10",
				pickupAddress: "909 Beech Rd",
				destination: "1010 Ivy St",
				cost: 11.7,
				coinsMined: 0.0000000029,
				distanceCovered: 2.8,
			},
			{
				date: "02-aug-2024",
				time: "11:55",
				pickupAddress: "111 Sycamore Ave",
				destination: "121 Willow Ct",
				cost: 10.2,
				coinsMined: 0.0000000026,
				distanceCovered: 1.7,
			},
			{
				date: "03-aug-2024",
				time: "10:25",
				pickupAddress: "131 Walnut St",
				destination: "141 Cherry Cir",
				cost: 16.8,
				coinsMined: 0.0000000034,
				distanceCovered: 5.3,
			},
			{
				date: "04-aug-2024",
				time: "09:15",
				pickupAddress: "151 Plum Ln",
				destination: "161 Grape St",
				cost: 7.9,
				coinsMined: 0.0000000017,
				distanceCovered: 1.2,
			},
			{
				date: "05-aug-2024",
				time: "08:05",
				pickupAddress: "171 Peach Pl",
				destination: "181 Orange Ct",
				cost: 6.5,
				coinsMined: 0.0000000014,
				distanceCovered: 0.8,
			},
			{
				date: "06-aug-2024",
				time: "18:40",
				pickupAddress: "191 Nectarine Rd",
				destination: "201 Lemon Cir",
				cost: 21.4,
				coinsMined: 0.0000000043,
				distanceCovered: 6.8,
			},
			{
				date: "07-aug-2024",
				time: "17:00",
				pickupAddress: "211 Kiwi Dr",
				destination: "221 Fig St",
				cost: 20.9,
				coinsMined: 0.0000000041,
				distanceCovered: 6.5,
			},
			{
				date: "08-aug-2024",
				time: "16:15",
				pickupAddress: "231 Pomegranate Ave",
				destination: "241 Papaya Ln",
				cost: 12.4,
				coinsMined: 0.0000000027,
				distanceCovered: 3.0,
			},
			{
				date: "09-aug-2024",
				time: "13:40",
				pickupAddress: "251 Persimmon St",
				destination: "261 Date Ct",
				cost: 8.6,
				coinsMined: 0.0000000019,
				distanceCovered: 1.5,
			},
			{
				date: "10-aug-2024",
				time: "19:55",
				pickupAddress: "271 Starfruit Pl",
				destination: "281 Mangosteen Rd",
				cost: 24.0,
				coinsMined: 0.000000005,
				distanceCovered: 7.8,
			},
			{
				date: "11-aug-2024",
				time: "21:20",
				pickupAddress: "291 Durian Cir",
				destination: "301 Rambutan St",
				cost: 17.1,
				coinsMined: 0.0000000036,
				distanceCovered: 5.4,
			},
			{
				date: "12-aug-2024",
				time: "07:50",
				pickupAddress: "311 Lychee Rd",
				destination: "321 Coconut Ave",
				cost: 9.3,
				coinsMined: 0.0000000021,
				distanceCovered: 1.4,
			},
			{
				date: "13-aug-2024",
				time: "08:30",
				pickupAddress: "331 Banana Pl",
				destination: "341 Plantain Ln",
				cost: 18.3,
				coinsMined: 0.0000000038,
				distanceCovered: 6.0,
			},
			{
				date: "14-aug-2024",
				time: "11:15",
				pickupAddress: "351 Melon St",
				destination: "361 Cantaloupe Rd",
				cost: 10.7,
				coinsMined: 0.0000000028,
				distanceCovered: 2.7,
			},
			{
				date: "15-aug-2024",
				time: "12:10",
				pickupAddress: "371 Honeydew Cir",
				destination: "381 Watermelon Ct",
				cost: 13.6,
				coinsMined: 0.0000000031,
				distanceCovered: 3.4,
			},
			{
				date: "16-aug-2024",
				time: "14:05",
				pickupAddress: "391 Berry Pl",
				destination: "401 Blueberry Ln",
				cost: 22.5,
				coinsMined: 0.0000000046,
				distanceCovered: 6.9,
			},
			{
				date: "17-aug-2024",
				time: "16:20",
				pickupAddress: "411 Cranberry Rd",
				destination: "421 Strawberry St",
				cost: 11.5,
				coinsMined: 0.0000000027,
				distanceCovered: 3.2,
			},
			{
				date: "18-aug-2024",
				time: "18:00",
				pickupAddress: "431 Raspberry Ave",
				destination: "441 Blackberry Cir",
				cost: 14.1,
				coinsMined: 0.0000000033,
				distanceCovered: 4.0,
			},
			{
				date: "19-aug-2024",
				time: "10:25",
				pickupAddress: "451 Gooseberry Pl",
				destination: "461 Huckleberry Rd",
				cost: 16.0,
				coinsMined: 0.0000000035,
				distanceCovered: 5.2,
			},
		],
	},
	{
		userId: 9123,
		email: "ethan.green@gmail.com",
		contactNo: 2348034567890,
		verification: "Unverified",
		reviews: 2.0,
		totalRides: 85,
		cancelledRides: 4,
		completedRides: 81,
		amountSpent: 40000,
	},
	{
		userId: 9124,
		email: "sophia.brown@gmail.com",
		contactNo: 2348045678901,
		verification: "Verified",
		reviews: 5.0,
		totalRides: 200,
		cancelledRides: 0,
		completedRides: 200,
		amountSpent: 95000,
	},
	{
		userId: 9125,
		email: "liam.scott@gmail.com",
		contactNo: 2348056789012,
		verification: "Unverified",
		reviews: 4.0,
		totalRides: 50,
		cancelledRides: 2,
		completedRides: 48,
		amountSpent: 25000,
	},
	{
		userId: 9126,
		email: "olivia.hall@gmail.com",
		contactNo: 2348067890123,
		verification: "Verified",
		reviews: 4.0,
		totalRides: 105,
		cancelledRides: 3,
		completedRides: 102,
		amountSpent: 46000,
	},
	{
		userId: 9127,
		email: "mason.clark@gmail.com",
		contactNo: 2348078901234,
		verification: "Verified",
		reviews: 3.0,
		totalRides: 67,
		cancelledRides: 5,
		completedRides: 62,
		amountSpent: 28000,
	},
	{
		userId: 9128,
		email: "ava.lopez@gmail.com",
		contactNo: 2348089012345,
		verification: "Unverified",
		reviews: 5.0,
		totalRides: 210,
		cancelledRides: 8,
		completedRides: 202,
		amountSpent: 98000,
	},
	{
		userId: 9129,
		email: "james.young@gmail.com",
		contactNo: 2348090123456,
		verification: "Verified",
		reviews: 4.0,
		totalRides: 130,
		cancelledRides: 2,
		completedRides: 128,
		amountSpent: 61000,
	},
	{
		userId: 9130,
		email: "ella.king@gmail.com",
		contactNo: 2348101234567,
		verification: "Unverified",
		reviews: 4.0,
		totalRides: 85,
		cancelledRides: 3,
		completedRides: 82,
		amountSpent: 38000,
	},
	{
		userId: 9131,
		email: "lucas.walker@gmail.com",
		contactNo: 2348112345678,
		verification: "Verified",
		reviews: 4.0,
		totalRides: 175,
		cancelledRides: 6,
		completedRides: 169,
		amountSpent: 75000,
	},
	{
		userId: 9132,
		email: "isabella.mitchell@gmail.com",
		contactNo: 2348123456789,
		verification: "Unverified",
		reviews: 4.0,
		totalRides: 95,
		cancelledRides: 5,
		completedRides: 90,
		amountSpent: 42000,
	},
	{
		userId: 9133,
		email: "benjamin.perez@gmail.com",
		contactNo: 2348134567890,
		verification: "Unverified",
		reviews: 3.0,
		totalRides: 55,
		cancelledRides: 3,
		completedRides: 52,
		amountSpent: 23000,
	},
	{
		userId: 9134,
		email: "amelia.reed@gmail.com",
		contactNo: 2348145678901,
		verification: "Verified",
		reviews: 5.0,
		totalRides: 225,
		cancelledRides: 1,
		completedRides: 224,
		amountSpent: 103000,
	},
	{
		userId: 9135,
		email: "henry.baker@gmail.com",
		contactNo: 2348156789012,
		verification: "Unverified",
		reviews: 2.0,
		totalRides: 43,
		cancelledRides: 2,
		completedRides: 41,
		amountSpent: 19000,
	},
	{
		userId: 9136,
		email: "charlotte.rivera@gmail.com",
		contactNo: 2348167890123,
		verification: "Verified",
		reviews: 4.0,
		totalRides: 110,
		cancelledRides: 4,
		completedRides: 106,
		amountSpent: 50000,
	},
	{
		userId: 9137,
		email: "daniel.ward@gmail.com",
		contactNo: 2348178901234,
		verification: "Unverified",
		reviews: 3.0,
		totalRides: 68,
		cancelledRides: 2,
		completedRides: 66,
		amountSpent: 30000,
	},
	{
		userId: 9138,
		email: "harper.torres@gmail.com",
		contactNo: 2348189012345,
		verification: "Verified",
		reviews: 5.0,
		totalRides: 240,
		cancelledRides: 3,
		completedRides: 237,
		amountSpent: 109000,
	},
	{
		userId: 9139,
		email: "michael.sanchez@gmail.com",
		contactNo: 2348190123456,
		verification: "Unverified",
		reviews: 4.0,
		totalRides: 80,
		cancelledRides: 1,
		completedRides: 79,
		amountSpent: 37000,
	},
	{
		userId: 9140,
		email: "abigail.campbell@gmail.com",
		contactNo: 2348201234567,
		verification: "Unverified",
		reviews: 3.0,
		totalRides: 65,
		cancelledRides: 4,
		completedRides: 61,
		amountSpent: 29000,
	},
	{
		userId: 9141,
		email: "alex.jones@gmail.com",
		contactNo: 2348212345678,
		verification: "Verified",
		reviews: 5.0,
		totalRides: 250,
		cancelledRides: 0,
		completedRides: 250,
		amountSpent: 115000,
	},
	{
		userId: 9142,
		email: "emma.white@gmail.com",
		contactNo: 2348223456789,
		verification: "Verified",
		reviews: 4.0,
		totalRides: 190,
		cancelledRides: 5,
		completedRides: 185,
		amountSpent: 90000,
	},
];

export const reviewData: ReviewDataProps[] = [
	{
		userName: "John Ozuem",
		userDescription:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip",
		stars: 4,
	},
	{
		userName: "Joy Iyoha",
		userDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing",
		stars: 5,
	},
	{
		userName: "Akpan Idara",
		userDescription: "Lorem ipsum dolor sit amet.",
		stars: 2,
	},
	{
		userName: "Kate Isoko",
		userDescription: "Lorem ipsum",
		stars: 1,
	},
	{
		userName: "John Ozuem",
		userDescription:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip",
		stars: 4,
	},
	{
		userName: "Lizzy Kokoni",
		userDescription:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		stars: 3,
	},
	{
		userName: "Bill Isoko",
		userDescription: "Lorem ipsum",
		stars: 1,
	},
	{
		userName: "John Ozuem",
		userDescription:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip",
		stars: 4,
	},
	{
		userName: "Joy Rice",
		userDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing",
		stars: 5,
	},
	{
		userName: "Akpan Idara",
		userDescription: "Lorem ipsum dolor sit amet.",
		stars: 2,
	},
	{
		userName: "Lizzy Kokoni",
		userDescription:
			"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
		stars: 3,
	},
	{
		userName: "Brown Iyoha",
		userDescription: "Lorem ipsum dolor sit amet, consectetur adipiscing",
		stars: 5,
	},
	{
		userName: "White Idara",
		userDescription: "Lorem ipsum dolor sit amet.",
		stars: 2,
	},
	{
		userName: "McClaren Isoko",
		userDescription: "Lorem ipsum",
		stars: 1,
	},
];

export const driverData: DriverDataProps[] = [
	{
		driverId: 9121,
		email: "driver1@example.com",
		contactNo: "2347098765432",
		verificationStatus: "Verified",
		reviews: 5,
	},
	{
		driverId: 9122,
		email: "driver2@example.com",
		contactNo: "2347098765433",
		verificationStatus: "Unverified",
		reviews: 4,
	},
	{
		driverId: 9123,
		email: "driver3@example.com",
		contactNo: "2347098765434",
		verificationStatus: "Verified",
		reviews: 3,
	},
	{
		driverId: 9124,
		email: "driver4@example.com",
		contactNo: "2347098765435",
		verificationStatus: "Verified",
		reviews: 2,
	},
	{
		driverId: 9125,
		email: "driver5@example.com",
		contactNo: "2347098765436",
		verificationStatus: "Unverified",
		reviews: 1,
	},
	{
		driverId: 9126,
		email: "driver6@example.com",
		contactNo: "2347098765437",
		verificationStatus: "Verified",
		reviews: 5,
	},
	{
		driverId: 9127,
		email: "driver7@example.com",
		contactNo: "2347098765438",
		verificationStatus: "Unverified",
		reviews: 4,
	},
	{
		driverId: 9128,
		email: "driver8@example.com",
		contactNo: "2347098765439",
		verificationStatus: "Verified",
		reviews: 3,
	},
	{
		driverId: 9129,
		email: "driver9@example.com",
		contactNo: "2347098765440",
		verificationStatus: "Verified",
		reviews: 2,
	},
	{
		driverId: 9130,
		email: "driver10@example.com",
		contactNo: "2347098765441",
		verificationStatus: "Unverified",
		reviews: 1,
	},
	{
		driverId: 9131,
		email: "driver11@example.com",
		contactNo: "2347098765442",
		verificationStatus: "Verified",
		reviews: 5,
	},
	{
		driverId: 9132,
		email: "driver12@example.com",
		contactNo: "2347098765443",
		verificationStatus: "Unverified",
		reviews: 4,
	},
	{
		driverId: 9133,
		email: "driver13@example.com",
		contactNo: "2347098765444",
		verificationStatus: "Verified",
		reviews: 3,
	},
	{
		driverId: 9134,
		email: "driver14@example.com",
		contactNo: "2347098765445",
		verificationStatus: "Verified",
		reviews: 2,
	},
	{
		driverId: 9135,
		email: "driver15@example.com",
		contactNo: "2347098765446",
		verificationStatus: "Unverified",
		reviews: 1,
	},
	{
		driverId: 9136,
		email: "driver16@example.com",
		contactNo: "2347098765447",
		verificationStatus: "Verified",
		reviews: 5,
	},
	{
		driverId: 9137,
		email: "driver17@example.com",
		contactNo: "2347098765448",
		verificationStatus: "Unverified",
		reviews: 4,
	},
	{
		driverId: 9138,
		email: "driver18@example.com",
		contactNo: "2347098765449",
		verificationStatus: "Verified",
		reviews: 3,
	},
	{
		driverId: 9139,
		email: "driver19@example.com",
		contactNo: "2347098765450",
		verificationStatus: "Verified",
		reviews: 2,
	},
	{
		driverId: 9140,
		email: "driver20@example.com",
		contactNo: "2347098765451",
		verificationStatus: "Unverified",
		reviews: 1,
	},
]; //?

export const revenueData: RevenueDataProps[] = [
	{
		rideId: 9121,
		userName: "JohnDoe",
		totalAmount: 250.75,
		commission: 50,
		driversCommission: 25,
		data: [
			{
				rideType: "Clasic",
				driversName: "John Doe",
				rideAmount: 25.5,
				commission: 5.0,
				driversCommission: 20.5,
				paymentMethod: "Credit Card",
			},
			{
				rideType: "Economy",
				driversName: "Jane Smith",
				rideAmount: 40.0,
				commission: 8.0,
				driversCommission: 32.0,
				paymentMethod: "Cash",
			},
			{
				rideType: "Luxury",
				driversName: "Robert Brown",
				rideAmount: 15.75,
				commission: 3.0,
				driversCommission: 12.75,
				paymentMethod: "Mobile Payment",
			},
			{
				rideType: "Luxury",
				driversName: "Emily Davis",
				rideAmount: 60.0,
				commission: 12.0,
				driversCommission: 48.0,
				paymentMethod: "Credit Card",
			},
		],
	},
	{
		rideId: 9122,
		userName: "JaneSmith",
		totalAmount: 320.4,
		commission: 75,
		driversCommission: 50,
		data: [
			{
				rideType: "Economy",
				driversName: "John Doe",
				rideAmount: 25.5,
				commission: 5.0,
				driversCommission: 20.5,
				paymentMethod: "Credit Card",
			},

			{
				rideType: "Luxury",
				driversName: "Robert Brown",
				rideAmount: 15.75,
				commission: 3.0,
				driversCommission: 12.75,
				paymentMethod: "Mobile Payment",
			},
			{
				rideType: "Luxury",
				driversName: "Jane Smith",
				rideAmount: 40.0,
				commission: 8.0,
				driversCommission: 32.0,
				paymentMethod: "Cash",
			},
			{
				rideType: "Classic",
				driversName: "Emily Davis",
				rideAmount: 60.0,
				commission: 12.0,
				driversCommission: 48.0,
				paymentMethod: "Credit Card",
			},
		],
	},
	{
		rideId: 9123,
		userName: "PaulBrown",
		totalAmount: 150.0,
		commission: 30,
		driversCommission: 15,
	},
	{
		rideId: 9124,
		userName: "EmilyDavis",
		totalAmount: 540.25,
		commission: 100,
		driversCommission: 50,
	},
	{
		rideId: 9125,
		userName: "ChrisWilson",
		totalAmount: 410.5,
		commission: 40,
		driversCommission: 20,
	},
	{
		rideId: 9126,
		userName: "NancyMiller",
		totalAmount: 280.0,
		commission: 20,
		driversCommission: 10,
	},
	{
		rideId: 9127,
		userName: "SteveMoore",
		totalAmount: 630.9,
		commission: 100,
		driversCommission: 75,
	},
	{
		rideId: 9128,
		userName: "RachelTaylor",
		totalAmount: 330.1,
		commission: 25,
		driversCommission: 15,
	},
	{
		rideId: 9129,
		userName: "DavidAnderson",
		totalAmount: 460.35,
		commission: 60,
		driversCommission: 30,
	},
	{
		rideId: 9130,
		userName: "LindaThomas",
		totalAmount: 150.5,
		commission: 15,
		driversCommission: 5,
	},
	{
		rideId: 9131,
		userName: "MarkJackson",
		totalAmount: 300.8,
		commission: 45,
		driversCommission: 20,
	},
	{
		rideId: 9132,
		userName: "SusanWhite",
		totalAmount: 220.25,
		commission: 55,
		driversCommission: 25,
	},
	{
		rideId: 9133,
		userName: "KevinHarris",
		totalAmount: 120.6,
		commission: 10,
		driversCommission: 5,
	},
	{
		rideId: 9134,
		userName: "JessicaMartin",
		totalAmount: 505.0,
		commission: 85,
		driversCommission: 40,
	},
	{
		rideId: 9135,
		userName: "DanielThompson",
		totalAmount: 420.5,
		commission: 65,
		driversCommission: 35,
	},
	{
		rideId: 9136,
		userName: "LauraGarcia",
		totalAmount: 275.1,
		commission: 50,
		driversCommission: 30,
	},
	{
		rideId: 9137,
		userName: "JamesMartinez",
		totalAmount: 310.9,
		commission: 45,
		driversCommission: 25,
	},
	{
		rideId: 9138,
		userName: "SarahRobinson",
		totalAmount: 235.75,
		commission: 35,
		driversCommission: 20,
	},
	{
		rideId: 9139,
		userName: "BrianClark",
		totalAmount: 190.3,
		commission: 25,
		driversCommission: 15,
	},
	{
		rideId: 9140,
		userName: "KarenRodriguez",
		totalAmount: 600.5,
		commission: 90,
		driversCommission: 60,
	},
];

export const sentMessagesData: { message: string; dateSent: string }[] = [
	{ message: "This is a very nice app", dateSent: "27/08/2024" },
	{
		message: "THis is so so lovely",
		dateSent: "19/09/2024",
	},
	{
		message: "Well i'm intruiged as this is so so lovely",
		dateSent: "19/09/2024",
	},
	{ message: "This is a very Beautiful app", dateSent: "27/08/2024" },
	{
		message: "THis is so so lovely",
		dateSent: "19/09/2024",
	},
	{
		message: "THis is so so lovely",
		dateSent: "19/09/2024",
	},
	{
		message: "Well i'm intruiged as this is so so lovely",
		dateSent: "19/09/2024",
	},
	{ message: "This is a very Beautiful app", dateSent: "27/08/2024" },
];

export const vehicleDatabaseData: VehicleDatabaseProps[] = [
	{ driverId: 1, vehicleType: "Sedan", vehicleNumber: "ABC1234" },
	{ driverId: 2, vehicleType: "SUV", vehicleNumber: "XYZ5678" },
	{ driverId: 3, vehicleType: "Truck", vehicleNumber: "JKL9101" },
	{ driverId: 4, vehicleType: "Sedan", vehicleNumber: "LMN2345" },
	{ driverId: 5, vehicleType: "SUV", vehicleNumber: "PQR6789" },
	{ driverId: 6, vehicleType: "Truck", vehicleNumber: "STU5432" },
	{ driverId: 7, vehicleType: "Motorbike", vehicleNumber: "GHI8765" },
	{ driverId: 8, vehicleType: "Sedan", vehicleNumber: "OPQ6781" },
	{ driverId: 9, vehicleType: "SUV", vehicleNumber: "VWX1092" },
	{ driverId: 10, vehicleType: "Truck", vehicleNumber: "ZAB5673" },
	{ driverId: 11, vehicleType: "Motorbike", vehicleNumber: "DEF8904" },
	{ driverId: 12, vehicleType: "Sedan", vehicleNumber: "MNO2346" },
	{ driverId: 13, vehicleType: "SUV", vehicleNumber: "RTS5439" },
	{ driverId: 14, vehicleType: "Truck", vehicleNumber: "WXZ3217" },
	{ driverId: 15, vehicleType: "Motorbike", vehicleNumber: "JKL0987" },
	{ driverId: 16, vehicleType: "Sedan", vehicleNumber: "OPW1290" },
	{ driverId: 17, vehicleType: "SUV", vehicleNumber: "PQL5678" },
	{ driverId: 18, vehicleType: "Truck", vehicleNumber: "RTU4321" },
	{ driverId: 19, vehicleType: "Motorbike", vehicleNumber: "HGF9867" },
	{ driverId: 20, vehicleType: "Sedan", vehicleNumber: "NBY2456" },
	{ driverId: 21, vehicleType: "SUV", vehicleNumber: "VWL7890" },
	{ driverId: 22, vehicleType: "Truck", vehicleNumber: "QRS5671" },
	{ driverId: 23, vehicleType: "Motorbike", vehicleNumber: "IJK4329" },
	{ driverId: 24, vehicleType: "Sedan", vehicleNumber: "LMN6548" },
	{ driverId: 25, vehicleType: "SUV", vehicleNumber: "PRS9876" },
	{ driverId: 26, vehicleType: "Truck", vehicleNumber: "TUV6543" },
	{ driverId: 27, vehicleType: "Motorbike", vehicleNumber: "UVW1029" },
	{ driverId: 28, vehicleType: "Sedan", vehicleNumber: "RTY7891" },
	{ driverId: 29, vehicleType: "SUV", vehicleNumber: "FGH5436" },
	{ driverId: 30, vehicleType: "Truck", vehicleNumber: "ZXW4325" },
];

export const ridesInvoiceData: RidesInvoiceDataProps[] = [
	{
		rideId: 1,
		driverName: "John Doe",
		userName: "Alice Johnson",
		startTime: "8:15am",
		endTime: "9:00am",
		data: [
			{
				date: "2024-09-20",
				pickUp: "123 Main St, New York, NY",
				dropOff: "456 Elm St, Brooklyn, NY",
				fare: 25.5,
				coinsMined: 5,
				distanceCovered: 12.4,
			},
			{
				date: "2024-09-21",
				pickUp: "789 Oak St, Queens, NY",
				dropOff: "101 Pine St, Manhattan, NY",
				fare: 18.75,
				coinsMined: 3,
				distanceCovered: 8.7,
			},
			{
				date: "2024-09-22",
				pickUp: "222 Maple Ave, Jersey City, NJ",
				dropOff: "333 Cedar Ave, Newark, NJ",
				fare: 35.0,
				coinsMined: 7,
				distanceCovered: 15.2,
			},
			{
				date: "2024-09-23",
				pickUp: "444 Birch Rd, Hoboken, NJ",
				dropOff: "555 Willow Rd, Weehawken, NJ",
				fare: 12.5,
				coinsMined: 2,
				distanceCovered: 5.6,
			},
			{
				date: "2024-09-24",
				pickUp: "666 Spruce Ln, New York, NY",
				dropOff: "777 Cypress Ln, Bronx, NY",
				fare: 22.3,
				coinsMined: 4,
				distanceCovered: 10.9,
			},
			{
				date: "2024-09-25",
				pickUp: "888 Cherry St, Brooklyn, NY",
				dropOff: "999 Peach St, Staten Island, NY",
				fare: 40.8,
				coinsMined: 8,
				distanceCovered: 20.3,
			},
			{
				date: "2024-09-26",
				pickUp: "321 Walnut Blvd, Queens, NY",
				dropOff: "654 Magnolia Blvd, New York, NY",
				fare: 30.45,
				coinsMined: 6,
				distanceCovered: 14.5,
			},
			{
				date: "2024-09-27",
				pickUp: "987 Ash Dr, Brooklyn, NY",
				dropOff: "432 Fir Dr, Bronx, NY",
				fare: 16.2,
				coinsMined: 3,
				distanceCovered: 7.8,
			},
			{
				date: "2024-09-28",
				pickUp: "543 Dogwood St, Manhattan, NY",
				dropOff: "210 Evergreen St, Queens, NY",
				fare: 27.6,
				coinsMined: 5,
				distanceCovered: 13.1,
			},
			{
				date: "2024-09-29",
				pickUp: "765 Palm St, Brooklyn, NY",
				dropOff: "432 Oakwood St, Staten Island, NY",
				fare: 50.0,
				coinsMined: 9,
				distanceCovered: 25.4,
			},
		],
	},
	{
		rideId: 2,
		driverName: "Mary Smith",
		userName: "Bob Williams",
		startTime: "10:30am",
		endTime: "11:15am",
		data: [
			{
				date: "2024-09-21",
				pickUp: "789 Oak St, Queens, NY",
				dropOff: "101 Pine St, Manhattan, NY",
				fare: 18.75,
				coinsMined: 3,
				distanceCovered: 8.7,
			},
			{
				date: "2024-09-22",
				pickUp: "222 Maple Ave, Jersey City, NJ",
				dropOff: "333 Cedar Ave, Newark, NJ",
				fare: 35.0,
				coinsMined: 7,
				distanceCovered: 15.2,
			},
			{
				date: "2024-09-23",
				pickUp: "444 Birch Rd, Hoboken, NJ",
				dropOff: "555 Willow Rd, Weehawken, NJ",
				fare: 12.5,
				coinsMined: 2,
				distanceCovered: 5.6,
			},
			{
				date: "2024-09-24",
				pickUp: "666 Spruce Ln, New York, NY",
				dropOff: "777 Cypress Ln, Bronx, NY",
				fare: 22.3,
				coinsMined: 4,
				distanceCovered: 10.9,
			},
			{
				date: "2024-09-25",
				pickUp: "888 Cherry St, Brooklyn, NY",
				dropOff: "999 Peach St, Staten Island, NY",
				fare: 40.8,
				coinsMined: 8,
				distanceCovered: 20.3,
			},
			{
				date: "2024-09-26",
				pickUp: "321 Walnut Blvd, Queens, NY",
				dropOff: "654 Magnolia Blvd, New York, NY",
				fare: 30.45,
				coinsMined: 6,
				distanceCovered: 14.5,
			},
			{
				date: "2024-09-27",
				pickUp: "987 Ash Dr, Brooklyn, NY",
				dropOff: "432 Fir Dr, Bronx, NY",
				fare: 16.2,
				coinsMined: 3,
				distanceCovered: 7.8,
			},
			{
				date: "2024-09-28",
				pickUp: "543 Dogwood St, Manhattan, NY",
				dropOff: "210 Evergreen St, Queens, NY",
				fare: 27.6,
				coinsMined: 5,
				distanceCovered: 13.1,
			},
			{
				date: "2024-09-29",
				pickUp: "765 Palm St, Brooklyn, NY",
				dropOff: "432 Oakwood St, Staten Island, NY",
				fare: 50.0,
				coinsMined: 9,
				distanceCovered: 25.4,
			},
		],
	},
	{
		rideId: 3,
		driverName: "James Brown",
		userName: "Charlie Miller",
		startTime: "1:00pm",
		endTime: "1:45pm",
	},
	{
		rideId: 4,
		driverName: "Patricia Garcia",
		userName: "David Wilson",
		startTime: "2:10pm",
		endTime: "2:50pm",
	},
	{
		rideId: 5,
		driverName: "Robert Martinez",
		userName: "Emily Davis",
		startTime: "7:30am",
		endTime: "8:10am",
	},
	{
		rideId: 6,
		driverName: "Linda Hernandez",
		userName: "Frank Thompson",
		startTime: "9:45am",
		endTime: "10:30am",
	},
	{
		rideId: 7,
		driverName: "Michael Clark",
		userName: "Grace Lopez",
		startTime: "3:00pm",
		endTime: "3:40pm",
	},
	{
		rideId: 8,
		driverName: "Barbara Lee",
		userName: "Henry Hill",
		startTime: "4:15pm",
		endTime: "5:00pm",
	},
	{
		rideId: 9,
		driverName: "Paul Walker",
		userName: "Ivy Adams",
		startTime: "11:00am",
		endTime: "11:45am",
	},
	{
		rideId: 10,
		driverName: "Steven Young",
		userName: "Jack Baker",
		startTime: "12:20pm",
		endTime: "1:00pm",
	},
	{
		rideId: 11,
		driverName: "Sandra Hall",
		userName: "Kelly Gonzalez",
		startTime: "6:00pm",
		endTime: "6:45pm",
	},
	{
		rideId: 12,
		driverName: "Andrew Lewis",
		userName: "Liam Carter",
		startTime: "9:30am",
		endTime: "10:10am",
	},
	{
		rideId: 13,
		driverName: "Melissa Scott",
		userName: "Mia Roberts",
		startTime: "5:20pm",
		endTime: "6:00pm",
	},
	{
		rideId: 14,
		driverName: "Kevin Green",
		userName: "Nathan Perez",
		startTime: "7:10am",
		endTime: "7:50am",
	},
	{
		rideId: 15,
		driverName: "Cynthia King",
		userName: "Olivia Stewart",
		startTime: "8:00am",
		endTime: "8:45am",
	},
	{
		rideId: 16,
		driverName: "Brian Adams",
		userName: "Peter Rivera",
		startTime: "1:30pm",
		endTime: "2:15pm",
	},
	{
		rideId: 17,
		driverName: "Rebecca Nelson",
		userName: "Quinn Rogers",
		startTime: "10:00am",
		endTime: "10:45am",
	},
	{
		rideId: 18,
		driverName: "Joshua Flores",
		userName: "Rachel Powell",
		startTime: "2:45pm",
		endTime: "3:30pm",
	},
	{
		rideId: 19,
		driverName: "Susan Mitchell",
		userName: "Sam Russell",
		startTime: "4:00pm",
		endTime: "4:40pm",
	},
	{
		rideId: 20,
		driverName: "Charles Campbell",
		userName: "Tina Martinez",
		startTime: "7:00am",
		endTime: "7:45am",
	},
	{
		rideId: 21,
		driverName: "Amy Ward",
		userName: "Umar White",
		startTime: "5:45pm",
		endTime: "6:30pm",
	},
	{
		rideId: 22,
		driverName: "Daniel Phillips",
		userName: "Vera Sanchez",
		startTime: "12:00pm",
		endTime: "12:40pm",
	},
	{
		rideId: 23,
		driverName: "Laura Parker",
		userName: "Will Ross",
		startTime: "11:15am",
		endTime: "12:00pm",
	},
	{
		rideId: 24,
		driverName: "Matthew Evans",
		userName: "Xander Bryant",
		startTime: "3:30pm",
		endTime: "4:15pm",
	},
	{
		rideId: 25,
		driverName: "Helen Rivera",
		userName: "Yara Bell",
		startTime: "6:15am",
		endTime: "7:00am",
	},
];

export const hotelsData: HangoutsHotelsProps[] = [
	{
		id: 1,
		hotelName: "Sunset Bay Resort",
		totalRooms: 100,
		availableRooms: 20,
		occupiedRooms: 70,
		reservedRooms: 10,
		monthRevenue: 150000,
		totalRevenue: 450000,
		data: [
			{
				noOfBoookingsToday: 12,
				noOfBookingsThisWeek: 45,
				noOfBookingsThisMonth: 120,
				noOfCancellationsToday: 1,
				noOfCancellationsThisWeek: 4,
				noOfCancellationsThisMonth: 10,
				revenueSoFar: 50000,
				noOfBookings: 120,
				noOfCancellation: 10,
				revenueThisMonth: 50000,
				percentRemitted: 15,
			},
			{
				noOfBoookingsToday: 10,
				noOfBookingsThisWeek: 35,
				noOfBookingsThisMonth: 85,
				noOfCancellationsToday: 2,
				noOfCancellationsThisWeek: 5,
				noOfCancellationsThisMonth: 8,
				revenueSoFar: 35000,
				noOfBookings: 85,
				noOfCancellation: 8,
				revenueThisMonth: 35000,
				percentRemitted: 10,
			},
		],
	},
	{
		id: 2,
		hotelName: "Oceanview Hotel",
		totalRooms: 80,
		availableRooms: 25,
		occupiedRooms: 45,
		reservedRooms: 10,
		monthRevenue: 120000,
		totalRevenue: 350000,
		data: [
			{
				noOfBoookingsToday: 15,
				noOfBookingsThisWeek: 50,
				noOfBookingsThisMonth: 150,
				noOfCancellationsToday: 3,
				noOfCancellationsThisWeek: 5,
				noOfCancellationsThisMonth: 12,
				revenueSoFar: 60000,
				noOfBookings: 150,
				noOfCancellation: 12,
				revenueThisMonth: 60000,
				percentRemitted: 20,
			},
			{
				noOfBoookingsToday: 8,
				noOfBookingsThisWeek: 30,
				noOfBookingsThisMonth: 90,
				noOfCancellationsToday: 1,
				noOfCancellationsThisWeek: 3,
				noOfCancellationsThisMonth: 6,
				revenueSoFar: 42000,
				noOfBookings: 90,
				noOfCancellation: 6,
				revenueThisMonth: 42000,
				percentRemitted: 12,
			},
		],
	},
	{
		id: 3,
		hotelName: "Mountain Peak Lodge",
		totalRooms: 60,
		availableRooms: 5,
		occupiedRooms: 50,
		reservedRooms: 5,
		monthRevenue: 90000,
		totalRevenue: 270000,
		data: [
			{
				noOfBoookingsToday: 13,
				noOfBookingsThisWeek: 40,
				noOfBookingsThisMonth: 110,
				noOfCancellationsToday: 2,
				noOfCancellationsThisWeek: 4,
				noOfCancellationsThisMonth: 10,
				revenueSoFar: 46000,
				noOfBookings: 110,
				noOfCancellation: 10,
				revenueThisMonth: 46000,
				percentRemitted: 15,
			},
		],
	},
	{
		id: 4,
		hotelName: "City Lights Inn",
		totalRooms: 150,
		availableRooms: 40,
		occupiedRooms: 90,
		reservedRooms: 20,
		monthRevenue: 200000,
		totalRevenue: 500000,
		data: [
			{
				noOfBoookingsToday: 20,
				noOfBookingsThisWeek: 70,
				noOfBookingsThisMonth: 200,
				noOfCancellationsToday: 5,
				noOfCancellationsThisWeek: 8,
				noOfCancellationsThisMonth: 15,
				revenueSoFar: 90000,
				noOfBookings: 200,
				noOfCancellation: 15,
				revenueThisMonth: 90000,
				percentRemitted: 25,
			},
		],
	},
	{
		id: 5,
		hotelName: "Riverside Retreat",
		totalRooms: 90,
		availableRooms: 10,
		occupiedRooms: 70,
		reservedRooms: 10,
		monthRevenue: 130000,
		totalRevenue: 350000,
		data: [
			{
				noOfBoookingsToday: 12,
				noOfBookingsThisWeek: 45,
				noOfBookingsThisMonth: 100,
				noOfCancellationsToday: 1,
				noOfCancellationsThisWeek: 4,
				noOfCancellationsThisMonth: 7,
				revenueSoFar: 60000,
				noOfBookings: 100,
				noOfCancellation: 7,
				revenueThisMonth: 60000,
				percentRemitted: 18,
			},
		],
	},
	{
		id: 6,
		hotelName: "Palm Grove Resort",
		totalRooms: 120,
		availableRooms: 30,
		occupiedRooms: 80,
		reservedRooms: 10,
		monthRevenue: 170000,
		totalRevenue: 400000,
		data: [
			{
				noOfBoookingsToday: 18,
				noOfBookingsThisWeek: 60,
				noOfBookingsThisMonth: 120,
				noOfCancellationsToday: 3,
				noOfCancellationsThisWeek: 6,
				noOfCancellationsThisMonth: 10,
				revenueSoFar: 75000,
				noOfBookings: 120,
				noOfCancellation: 10,
				revenueThisMonth: 75000,
				percentRemitted: 20,
			},
		],
	},
	{
		id: 7,
		hotelName: "Lakeside Hotel",
		totalRooms: 70,
		availableRooms: 15,
		occupiedRooms: 50,
		reservedRooms: 5,
		monthRevenue: 110000,
		totalRevenue: 300000,
		data: [
			{
				noOfBoookingsToday: 10,
				noOfBookingsThisWeek: 30,
				noOfBookingsThisMonth: 90,
				noOfCancellationsToday: 1,
				noOfCancellationsThisWeek: 3,
				noOfCancellationsThisMonth: 5,
				revenueSoFar: 48000,
				noOfBookings: 90,
				noOfCancellation: 5,
				revenueThisMonth: 48000,
				percentRemitted: 12,
			},
		],
	},
	{
		id: 8,
		hotelName: "Desert Sands Inn",
		totalRooms: 85,
		availableRooms: 18,
		occupiedRooms: 60,
		reservedRooms: 7,
		monthRevenue: 140000,
		totalRevenue: 380000,
		data: [
			{
				noOfBoookingsToday: 14,
				noOfBookingsThisWeek: 50,
				noOfBookingsThisMonth: 110,
				noOfCancellationsToday: 2,
				noOfCancellationsThisWeek: 5,
				noOfCancellationsThisMonth: 9,
				revenueSoFar: 58000,
				noOfBookings: 110,
				noOfCancellation: 9,
				revenueThisMonth: 58000,
				percentRemitted: 15,
			},
		],
	},
	{
		id: 9,
		hotelName: "Forest Hills Lodge",
		totalRooms: 65,
		availableRooms: 5,
		occupiedRooms: 55,
		reservedRooms: 5,
		monthRevenue: 95000,
		totalRevenue: 280000,
		data: [
			{
				noOfBoookingsToday: 8,
				noOfBookingsThisWeek: 30,
				noOfBookingsThisMonth: 75,
				noOfCancellationsToday: 1,
				noOfCancellationsThisWeek: 2,
				noOfCancellationsThisMonth: 5,
				revenueSoFar: 30000,
				noOfBookings: 75,
				noOfCancellation: 5,
				revenueThisMonth: 30000,
				percentRemitted: 10,
			},
		],
	},
	{
		id: 10,
		hotelName: "Blue Lagoon Hotel",
		totalRooms: 100,
		availableRooms: 20,
		occupiedRooms: 70,
		reservedRooms: 10,
		monthRevenue: 155000,
		totalRevenue: 420000,
		data: [
			{
				noOfBoookingsToday: 12,
				noOfBookingsThisWeek: 45,
				noOfBookingsThisMonth: 100,
				noOfCancellationsToday: 2,
				noOfCancellationsThisWeek: 4,
				noOfCancellationsThisMonth: 7,
				revenueSoFar: 60000,
				noOfBookings: 100,
				noOfCancellation: 7,
				revenueThisMonth: 60000,
				percentRemitted: 18,
			},
		],
	},
];

export const loungesData: HangoutsLoungesProps[] = [
	{
		id: 1,
		loungeName: "Skyline Lounge",
		totalTables: 50,
		availableTables: 15,
		occupiedTables: 30,
		reservedTables: 5,
		monthRevenue: 120000,
		totalRevenue: 400000,
		data: [
			{
				noOfBoookingsToday: 8,
				noOfBookingsThisWeek: 35,
				noOfBookingsThisMonth: 120,
				noOfCancellationsToday: 1,
				noOfCancellationsThisWeek: 4,
				noOfCancellationsThisMonth: 12,
				revenueSoFar: 50000,
				noOfBookings: 120,
				noOfCancellation: 12,
				revenueThisMonth: 50000,
				percentRemitted: 15,
			},
			{
				noOfBoookingsToday: 5,
				noOfBookingsThisWeek: 28,
				noOfBookingsThisMonth: 85,
				noOfCancellationsToday: 2,
				noOfCancellationsThisWeek: 5,
				noOfCancellationsThisMonth: 10,
				revenueSoFar: 35000,
				noOfBookings: 85,
				noOfCancellation: 10,
				revenueThisMonth: 35000,
				percentRemitted: 10,
			},
			{
				noOfBoookingsToday: 12,
				noOfBookingsThisWeek: 50,
				noOfBookingsThisMonth: 150,
				noOfCancellationsToday: 3,
				noOfCancellationsThisWeek: 7,
				noOfCancellationsThisMonth: 15,
				revenueSoFar: 60000,
				noOfBookings: 150,
				noOfCancellation: 15,
				revenueThisMonth: 60000,
				percentRemitted: 20,
			},
			{
				noOfBoookingsToday: 7,
				noOfBookingsThisWeek: 40,
				noOfBookingsThisMonth: 90,
				noOfCancellationsToday: 2,
				noOfCancellationsThisWeek: 6,
				noOfCancellationsThisMonth: 10,
				revenueSoFar: 42000,
				noOfBookings: 90,
				noOfCancellation: 10,
				revenueThisMonth: 42000,
				percentRemitted: 12,
			},
			{
				noOfBoookingsToday: 4,
				noOfBookingsThisWeek: 25,
				noOfBookingsThisMonth: 70,
				noOfCancellationsToday: 1,
				noOfCancellationsThisWeek: 3,
				noOfCancellationsThisMonth: 5,
				revenueSoFar: 28000,
				noOfBookings: 70,
				noOfCancellation: 5,
				revenueThisMonth: 28000,
				percentRemitted: 8,
			},
			{
				noOfBoookingsToday: 10,
				noOfBookingsThisWeek: 48,
				noOfBookingsThisMonth: 110,
				noOfCancellationsToday: 2,
				noOfCancellationsThisWeek: 5,
				noOfCancellationsThisMonth: 8,
				revenueSoFar: 52000,
				noOfBookings: 110,
				noOfCancellation: 8,
				revenueThisMonth: 52000,
				percentRemitted: 18,
			},
		],
	},
	{
		id: 2,
		loungeName: "The Peak Lounge",
		totalTables: 40,
		availableTables: 10,
		occupiedTables: 25,
		reservedTables: 5,
		monthRevenue: 90000,
		totalRevenue: 350000,
		data: [
			{
				noOfBoookingsToday: 7,
				noOfBookingsThisWeek: 30,
				noOfBookingsThisMonth: 100,
				noOfCancellationsToday: 1,
				noOfCancellationsThisWeek: 3,
				noOfCancellationsThisMonth: 8,
				revenueSoFar: 45000,
				noOfBookings: 100,
				noOfCancellation: 8,
				revenueThisMonth: 45000,
				percentRemitted: 15,
			},
			{
				noOfBoookingsToday: 6,
				noOfBookingsThisWeek: 32,
				noOfBookingsThisMonth: 90,
				noOfCancellationsToday: 1,
				noOfCancellationsThisWeek: 3,
				noOfCancellationsThisMonth: 6,
				revenueSoFar: 42000,
				noOfBookings: 90,
				noOfCancellation: 6,
				revenueThisMonth: 42000,
				percentRemitted: 12,
			},
			{
				noOfBoookingsToday: 5,
				noOfBookingsThisWeek: 28,
				noOfBookingsThisMonth: 80,
				noOfCancellationsToday: 1,
				noOfCancellationsThisWeek: 4,
				noOfCancellationsThisMonth: 7,
				revenueSoFar: 40000,
				noOfBookings: 80,
				noOfCancellation: 7,
				revenueThisMonth: 40000,
				percentRemitted: 14,
			},
			{
				noOfBoookingsToday: 8,
				noOfBookingsThisWeek: 36,
				noOfBookingsThisMonth: 110,
				noOfCancellationsToday: 2,
				noOfCancellationsThisWeek: 5,
				noOfCancellationsThisMonth: 10,
				revenueSoFar: 47000,
				noOfBookings: 110,
				noOfCancellation: 10,
				revenueThisMonth: 47000,
				percentRemitted: 16,
			},
			{
				noOfBoookingsToday: 9,
				noOfBookingsThisWeek: 38,
				noOfBookingsThisMonth: 115,
				noOfCancellationsToday: 3,
				noOfCancellationsThisWeek: 7,
				noOfCancellationsThisMonth: 12,
				revenueSoFar: 48000,
				noOfBookings: 115,
				noOfCancellation: 12,
				revenueThisMonth: 48000,
				percentRemitted: 18,
			},
			{
				noOfBoookingsToday: 4,
				noOfBookingsThisWeek: 20,
				noOfBookingsThisMonth: 70,
				noOfCancellationsToday: 1,
				noOfCancellationsThisWeek: 3,
				noOfCancellationsThisMonth: 5,
				revenueSoFar: 35000,
				noOfBookings: 70,
				noOfCancellation: 5,
				revenueThisMonth: 35000,
				percentRemitted: 10,
			},
		],
	},
	{
		id: 3,
		loungeName: "Zenith Lounge",
		totalTables: 35,
		availableTables: 8,
		occupiedTables: 22,
		reservedTables: 5,
		monthRevenue: 75000,
		totalRevenue: 280000,
		data: [
			{
				noOfBoookingsToday: 6,
				noOfBookingsThisWeek: 27,
				noOfBookingsThisMonth: 95,
				noOfCancellationsToday: 1,
				noOfCancellationsThisWeek: 3,
				noOfCancellationsThisMonth: 7,
				revenueSoFar: 38000,
				noOfBookings: 95,
				noOfCancellation: 7,
				revenueThisMonth: 38000,
				percentRemitted: 13,
			},
		],
	},
];
export const restaurantsData: HangoutsRestaurantsProps[] = [
	{
		id: 1,
		restaurantName: "Gourmet Bistro",
		totalTables: 60,
		availableTables: 20,
		occupiedTables: 30,
		reservedTables: 10,
		monthRevenue: 200000,
		totalRevenue: 600000,
		data: [
			{
				noOfBoookingsToday: 15,
				noOfBookingsThisWeek: 70,
				noOfBookingsThisMonth: 300,
				noOfCancellationsToday: 2,
				noOfCancellationsThisWeek: 5,
				noOfCancellationsThisMonth: 20,
				revenueSoFar: 70000,
				noOfBookings: 300,
				noOfCancellation: 20,
				revenueThisMonth: 70000,
				percentRemitted: 20,
			},
			{
				noOfBoookingsToday: 12,
				noOfBookingsThisWeek: 60,
				noOfBookingsThisMonth: 280,
				noOfCancellationsToday: 1,
				noOfCancellationsThisWeek: 3,
				noOfCancellationsThisMonth: 15,
				revenueSoFar: 65000,
				noOfBookings: 280,
				noOfCancellation: 15,
				revenueThisMonth: 65000,
				percentRemitted: 18,
			},
			{
				noOfBoookingsToday: 10,
				noOfBookingsThisWeek: 50,
				noOfBookingsThisMonth: 250,
				noOfCancellationsToday: 0,
				noOfCancellationsThisWeek: 2,
				noOfCancellationsThisMonth: 10,
				revenueSoFar: 60000,
				noOfBookings: 250,
				noOfCancellation: 10,
				revenueThisMonth: 60000,
				percentRemitted: 15,
			},
		],
	},
	{
		id: 2,
		restaurantName: "Savory Delights",
		totalTables: 80,
		availableTables: 25,
		occupiedTables: 45,
		reservedTables: 10,
		monthRevenue: 180000,
		totalRevenue: 500000,
		data: [
			{
				noOfBoookingsToday: 8,
				noOfBookingsThisWeek: 40,
				noOfBookingsThisMonth: 200,
				noOfCancellationsToday: 1,
				noOfCancellationsThisWeek: 4,
				noOfCancellationsThisMonth: 15,
				revenueSoFar: 55000,
				noOfBookings: 200,
				noOfCancellation: 15,
				revenueThisMonth: 55000,
				percentRemitted: 18,
			},
			{
				noOfBoookingsToday: 5,
				noOfBookingsThisWeek: 35,
				noOfBookingsThisMonth: 180,
				noOfCancellationsToday: 0,
				noOfCancellationsThisWeek: 2,
				noOfCancellationsThisMonth: 8,
				revenueSoFar: 50000,
				noOfBookings: 180,
				noOfCancellation: 8,
				revenueThisMonth: 50000,
				percentRemitted: 17,
			},
			{
				noOfBoookingsToday: 7,
				noOfBookingsThisWeek: 42,
				noOfBookingsThisMonth: 190,
				noOfCancellationsToday: 1,
				noOfCancellationsThisWeek: 3,
				noOfCancellationsThisMonth: 12,
				revenueSoFar: 53000,
				noOfBookings: 190,
				noOfCancellation: 12,
				revenueThisMonth: 53000,
				percentRemitted: 16,
			},
		],
	},
	{
		id: 3,
		restaurantName: "Taste of Italy",
		totalTables: 70,
		availableTables: 15,
		occupiedTables: 45,
		reservedTables: 10,
		monthRevenue: 210000,
		totalRevenue: 700000,
		data: [
			{
				noOfBoookingsToday: 20,
				noOfBookingsThisWeek: 100,
				noOfBookingsThisMonth: 350,
				noOfCancellationsToday: 3,
				noOfCancellationsThisWeek: 5,
				noOfCancellationsThisMonth: 25,
				revenueSoFar: 90000,
				noOfBookings: 350,
				noOfCancellation: 25,
				revenueThisMonth: 90000,
				percentRemitted: 22,
			},
			{
				noOfBoookingsToday: 15,
				noOfBookingsThisWeek: 90,
				noOfBookingsThisMonth: 320,
				noOfCancellationsToday: 2,
				noOfCancellationsThisWeek: 4,
				noOfCancellationsThisMonth: 20,
				revenueSoFar: 85000,
				noOfBookings: 320,
				noOfCancellation: 20,
				revenueThisMonth: 85000,
				percentRemitted: 21,
			},
			{
				noOfBoookingsToday: 12,
				noOfBookingsThisWeek: 85,
				noOfBookingsThisMonth: 310,
				noOfCancellationsToday: 1,
				noOfCancellationsThisWeek: 2,
				noOfCancellationsThisMonth: 15,
				revenueSoFar: 80000,
				noOfBookings: 310,
				noOfCancellation: 15,
				revenueThisMonth: 80000,
				percentRemitted: 20,
			},
		],
	},
	{
		id: 4,
		restaurantName: "Asian Fusion",
		totalTables: 65,
		availableTables: 18,
		occupiedTables: 35,
		reservedTables: 12,
		monthRevenue: 175000,
		totalRevenue: 550000,
		data: [
			{
				noOfBoookingsToday: 18,
				noOfBookingsThisWeek: 60,
				noOfBookingsThisMonth: 250,
				noOfCancellationsToday: 2,
				noOfCancellationsThisWeek: 4,
				noOfCancellationsThisMonth: 18,
				revenueSoFar: 60000,
				noOfBookings: 250,
				noOfCancellation: 18,
				revenueThisMonth: 60000,
				percentRemitted: 16,
			},
			{
				noOfBoookingsToday: 20,
				noOfBookingsThisWeek: 70,
				noOfBookingsThisMonth: 260,
				noOfCancellationsToday: 1,
				noOfCancellationsThisWeek: 5,
				noOfCancellationsThisMonth: 20,
				revenueSoFar: 62000,
				noOfBookings: 260,
				noOfCancellation: 20,
				revenueThisMonth: 62000,
				percentRemitted: 17,
			},
		],
	},
	{
		id: 5,
		restaurantName: "Barbecue Haven",
		totalTables: 80,
		availableTables: 30,
		occupiedTables: 40,
		reservedTables: 10,
		monthRevenue: 160000,
		totalRevenue: 500000,
		data: [
			{
				noOfBoookingsToday: 14,
				noOfBookingsThisWeek: 55,
				noOfBookingsThisMonth: 220,
				noOfCancellationsToday: 1,
				noOfCancellationsThisWeek: 3,
				noOfCancellationsThisMonth: 14,
				revenueSoFar: 57000,
				noOfBookings: 220,
				noOfCancellation: 14,
				revenueThisMonth: 57000,
				percentRemitted: 15,
			},
			{
				noOfBoookingsToday: 10,
				noOfBookingsThisWeek: 50,
				noOfBookingsThisMonth: 200,
				noOfCancellationsToday: 2,
				noOfCancellationsThisWeek: 5,
				noOfCancellationsThisMonth: 16,
				revenueSoFar: 55000,
				noOfBookings: 200,
				noOfCancellation: 16,
				revenueThisMonth: 55000,
				percentRemitted: 14,
			},
		],
	},
	{
		id: 6,
		restaurantName: "Cozy Corner",
		totalTables: 50,
		availableTables: 20,
		occupiedTables: 25,
		reservedTables: 5,
		monthRevenue: 120000,
		totalRevenue: 350000,
		data: [
			{
				noOfBoookingsToday: 9,
				noOfBookingsThisWeek: 40,
				noOfBookingsThisMonth: 150,
				noOfCancellationsToday: 1,
				noOfCancellationsThisWeek: 3,
				noOfCancellationsThisMonth: 10,
				revenueSoFar: 45000,
				noOfBookings: 150,
				noOfCancellation: 10,
				revenueThisMonth: 45000,
				percentRemitted: 12,
			},
			{
				noOfBoookingsToday: 6,
				noOfBookingsThisWeek: 35,
				noOfBookingsThisMonth: 140,
				noOfCancellationsToday: 0,
				noOfCancellationsThisWeek: 2,
				noOfCancellationsThisMonth: 8,
				revenueSoFar: 40000,
				noOfBookings: 140,
				noOfCancellation: 8,
				revenueThisMonth: 40000,
				percentRemitted: 10,
			},
		],
	},
	{
		id: 7,
		restaurantName: "Vegetarian Delights",
		totalTables: 30,
		availableTables: 10,
		occupiedTables: 15,
		reservedTables: 5,
		monthRevenue: 90000,
		totalRevenue: 300000,
		data: [
			{
				noOfBoookingsToday: 5,
				noOfBookingsThisWeek: 25,
				noOfBookingsThisMonth: 100,
				noOfCancellationsToday: 0,
				noOfCancellationsThisWeek: 1,
				noOfCancellationsThisMonth: 5,
				revenueSoFar: 30000,
				noOfBookings: 100,
				noOfCancellation: 5,
				revenueThisMonth: 30000,
				percentRemitted: 8,
			},
			{
				noOfBoookingsToday: 4,
				noOfBookingsThisWeek: 20,
				noOfBookingsThisMonth: 90,
				noOfCancellationsToday: 1,
				noOfCancellationsThisWeek: 2,
				noOfCancellationsThisMonth: 4,
				revenueSoFar: 28000,
				noOfBookings: 90,
				noOfCancellation: 4,
				revenueThisMonth: 28000,
				percentRemitted: 7,
			},
		],
	},
	{
		id: 8,
		restaurantName: "Sweet Tooth",
		totalTables: 20,
		availableTables: 5,
		occupiedTables: 10,
		reservedTables: 5,
		monthRevenue: 80000,
		totalRevenue: 200000,
		data: [
			{
				noOfBoookingsToday: 3,
				noOfBookingsThisWeek: 15,
				noOfBookingsThisMonth: 50,
				noOfCancellationsToday: 1,
				noOfCancellationsThisWeek: 2,
				noOfCancellationsThisMonth: 3,
				revenueSoFar: 20000,
				noOfBookings: 50,
				noOfCancellation: 3,
				revenueThisMonth: 20000,
				percentRemitted: 5,
			},
			{
				noOfBoookingsToday: 4,
				noOfBookingsThisWeek: 12,
				noOfBookingsThisMonth: 45,
				noOfCancellationsToday: 1,
				noOfCancellationsThisWeek: 1,
				noOfCancellationsThisMonth: 2,
				revenueSoFar: 18000,
				noOfBookings: 45,
				noOfCancellation: 2,
				revenueThisMonth: 18000,
				percentRemitted: 4,
			},
		],
	},
	{
		id: 9,
		restaurantName: "Family Feast",
		totalTables: 50,
		availableTables: 15,
		occupiedTables: 25,
		reservedTables: 10,
		monthRevenue: 110000,
		totalRevenue: 320000,
		data: [
			{
				noOfBoookingsToday: 10,
				noOfBookingsThisWeek: 40,
				noOfBookingsThisMonth: 150,
				noOfCancellationsToday: 1,
				noOfCancellationsThisWeek: 3,
				noOfCancellationsThisMonth: 10,
				revenueSoFar: 45000,
				noOfBookings: 150,
				noOfCancellation: 10,
				revenueThisMonth: 45000,
				percentRemitted: 12,
			},
			{
				noOfBoookingsToday: 8,
				noOfBookingsThisWeek: 30,
				noOfBookingsThisMonth: 120,
				noOfCancellationsToday: 0,
				noOfCancellationsThisWeek: 2,
				noOfCancellationsThisMonth: 5,
				revenueSoFar: 40000,
				noOfBookings: 120,
				noOfCancellation: 5,
				revenueThisMonth: 40000,
				percentRemitted: 10,
			},
		],
	},
	{
		id: 10,
		restaurantName: "Royal Buffet",
		totalTables: 70,
		availableTables: 25,
		occupiedTables: 30,
		reservedTables: 15,
		monthRevenue: 250000,
		totalRevenue: 900000,
		data: [
			{
				noOfBoookingsToday: 25,
				noOfBookingsThisWeek: 120,
				noOfBookingsThisMonth: 400,
				noOfCancellationsToday: 4,
				noOfCancellationsThisWeek: 6,
				noOfCancellationsThisMonth: 30,
				revenueSoFar: 130000,
				noOfBookings: 400,
				noOfCancellation: 30,
				revenueThisMonth: 130000,
				percentRemitted: 25,
			},
			{
				noOfBoookingsToday: 20,
				noOfBookingsThisWeek: 100,
				noOfBookingsThisMonth: 380,
				noOfCancellationsToday: 3,
				noOfCancellationsThisWeek: 5,
				noOfCancellationsThisMonth: 25,
				revenueSoFar: 120000,
				noOfBookings: 380,
				noOfCancellation: 25,
				revenueThisMonth: 120000,
				percentRemitted: 24,
			},
		],
	},
];
